name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: npm install
        working-directory: ./backend
        run: npm install
      - name: Run tests
        working-directory: ./backend
        run: npm test
      - name: Run Backend
        working-directory: ./backend
        run: npm start
      - name: Run Tests
        working-directory: ./frontend
        run: npx cypress run